### ISSUE TITLE
E Mails are not sent.

### ISSUE THREAD

**Issue by thiagoromera** [aschroder/Magento-SMTP-Pro-Email-Extension#102]
I have a multistore installing and using the module in version 1.4xx. And everything was fine. So I upgrade to the latest version and realized that it does not work multistore. I removed and went back to the previous version. Since then transactional messages are not being sent. The RunTeste works, but the sale and delivery of messages not.

Any tips?

**Comment by sandermangel** [comment]
@thiagoromera could you provide some information like Magento version and any relevant errors from your logs. Also please verify the email cron works properly
