### ISSUE TITLE
I can't found the SMTP PRO on admin screen

### ISSUE THREAD

**Issue by agnello** [aschroder/Magento-SMTP-Pro-Email-Extension#103]
Hi guys,

I'm getting crazy because of this, I have installed this module through magento connnect and manually for magento 1.8.1.0.

No issues found on installation process, I disabled the cache, deleted the files from var/cache directory, made logout and login and all the normal process a lot of times but I can't see the SMTP PRO on admin screen.

I'm running a clean installation without any additional module, this is the first one.

COuld you please help me?

**Comment by aschroder** [comment]
does it show up in the list of modules under System > Config > Admin?

**Comment by boulderdave** [comment]
I have the same issue.  I'm using 1.9.0.1, have done what @agnello mentioned also.

@agnello - did you end up figuring it out?  @aschroder any help much appreciated :)
