### ISSUE TITLE
Cant save custom smtp settings with authentication

### ISSUE THREAD

**Issue by ghost** [aschroder/Magento-SMTP-Pro-Email-Extension#107]
When trying to configure the smtp custom settings I get a blank screen after saving.
However the blank screen only appears when I select the login future of the smtp setting, for some reason it does save when selecting no authentication. 
What is interesting is that the key in the url is changed after saving. After refreshing it goes back to the old key.

I'm looking forward to a reply from somebody with more knowledge and to solve this issue for other users.

**Comment by sandermangel** [comment]
@ghost please turn on error displaying or find any relevant errors in the exception log and share them here.
