### ISSUE TITLE
Not Multi-Store compatible

### ISSUE THREAD

**Issue by mvenghaus** [aschroder/Magento-SMTP-Pro-Email-Extension#109]
store/website in not transported to all places

**Comment by aschroder** [comment]
Yeh I have never tested this so it's not supported. Most people want this feature because their email service is too crappy to allow arbitrary from: address headers. In those cases I suggest just use a proper transactional email service.

**Comment by royduin** [comment]
I don't agree about your reason. Most mail servers don't allow this because of security/spam issues.
