### ISSUE TITLE
Error when pressing Run Self Test & No Emails being sent

### ISSUE THREAD

**Issue by magejunkie** [aschroder/Magento-SMTP-Pro-Email-Extension#113]
SMTP Pro Self Test Results
Sending test email to your contact form address: xyz@xyz.com from: xyz@gmail.com. Unable to send test email.
Exception message was: 5.7.9 Please log in with your web browser and then try again. Learn more at 5.7.9 https://support.google.com/mail/answer/78754 i7sm2476765igt.18 - gsmtp 
Please check the user guide for frequent error messages and their solutions.
Default templates exist.
Email communications are enabled.

**Comment by aschroder** [comment]
Did you do what is suggested in the error message already and still having
trouble with it?
"Exception message was: 5.7.9 Please log in with your web browser and then
try again. Learn more at 5.7.9
https://support.google.com/mail/answer/78754 i7sm2476765igt.18
- gsmtp"

**Comment by magejunkie** [comment]
I tried using the http://www.google.com/accounts/DisplayUnlockCaptcha but it doesn't seem to work either.

My cron.php was setup to run every 15 minutes, could that be triggering this issue?

**Comment by aschroder** [comment]
You may have to proxy through your server's IP to solve eh captcha and
unblock your IP.

or... stop using google personal email accounts for commercial
transactional email and start using a proper email service, they;re not
meant for this sort of thing and if you send high volumes of email this
will keep happening I think.

**Comment by magejunkie** [comment]
Which service do you suggest we use? We don't send large amount of emails daily.

**Comment by aschroder** [comment]
Well *ahem* I do have a premium extension that works rather nicely with
Amazon SES (magesend.com) - but you could look at services like Mandril,
SendGrid, MailUp etc too. There are dozens of email services to choose from.

**Comment by hubertperron** [comment]
I'm using Google Apps mail (business account) and had the same problem. You must allow "less secure apps" in the admin panel of gmail (https://support.google.com/accounts/answer/6010255?hl=en).
