### ISSUE TITLE
Error : Zend_Mail_Protocol_Exception with message " Email address is  not verified"

### ISSUE THREAD

**Issue by satishsojitra** [aschroder/Magento-SMTP-Pro-Email-Extension#117]
Hi 

I am using smtppro with custom SMTP settings. I am using Amazon SES where I have verified email address. While creating new account,confirmation email,order emails are not going but when I submitting contact form it's working fine.

Following is exception

exception 'Zend_Mail_Protocol_Exception' with message 'Message rejected: Email address is not verified.' in /var/www/lib/Zend/Mail/Protocol/Abstract.php:431
Stack trace:
#0 /var/www/lib/Zend/Mail/Protocol/Smtp.php(324): Zend_Mail_Protocol_Abstract->_expect(250, 600)
#1 /var/www/lib/Zend/Mail/Transport/Smtp.php(215): Zend_Mail_Protocol_Smtp->data
('To: =?utf-8?B?c...')
#2 /var/www/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp-
>_sendMail()
#3 /var/www/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Z
end_Mail))
#4 /var/www/app/code/local/Aschroder/SMTPPro/Model/Email/Template.php(132): Zend
_Mail->send(Object(Zend_Mail_Transport_Smtp))
#5 /var/www/app/code/core/Mage/Core/Model/Email/Template.php(508): Aschroder_SMT
PPro_Model_Email_Template->send(Array, Array, Array)
#6 /var/www/app/code/core/Mage/Core/Model/Email/Template/Mailer.php(84): Mage_Co
re_Model_Email_Template->sendTransactional('6', 'general', Array, Array, Array,
'1')
#7 /var/www/app/code/local/Mage/Customer/Model/Customer.php(677): Mage_Core_Mode
l_Email_Template_Mailer->send()
#8 /var/www/app/code/local/Mage/Customer/Model/Customer.php(604): Mage_Customer_
Model_Customer->_sendEmailTemplate('customer/create...', 'customer/create...', A
rray, '1')
#9 /var/www/app/code/core/Mage/Customer/controllers/AccountController.php(642):
Mage_Customer_Model_Customer->sendNewAccountEmail('confirmation', '', '1')
#10 /var/www/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cus
tomer_AccountController->confirmationAction()
#11 /var/www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250):
 Mage_Core_Controller_Varien_Action->dispatch('confirmation')
#12 /var/www/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core
_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Ht
tp))
#13 /var/www/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Va
rien_Front->dispatch()
#14 /var/www/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /var/www/index.php(87): Mage::run('', 'store')
#16 {main}

Please help me out to solve this issue.

**Comment by jay-saint** [comment]
I am receiving the same problem.  Did anyone ever sort this out?  I get this in my logs about 3 times a day.  Order confirmation emails are going out, but share with fried emails are not sending.

**Comment by satishsojitra** [comment]
Hi Jay
I have figured out the solution. It's not extension fault. In my case it was problem in Amazon SES. SES works once you are opened SES it is by default in sandbox mode. So sandbox mode required to all email ids( FROM & TO) should be verified first. To move sandbox SES to product SES you need to open support case to amazon admin panel and need to apply for increase sending limit for SES account. Once your SES limit increase your account will move to production automatically and no need to verify ( FROM & TO ) email ids.
please us this links to read more:
docs.aws.amazon.com/ses/latest/DeveloperGuide/increase-sending-limits.html

Note: you need to initially verify your FROM emails in your amazon region.

**Comment by jay-saint** [comment]
Thank you for updating this issue, I am glad this solved the problem for you with SES.
We are currently sending email using an account on our business Office365 account, so this does not seem to be the problem.

**Comment by aschroder** [comment]
closing as solved. 

In any case messages like:
Message rejected: Email address is not verified

Are likely coming back from your email service/server and point to configuration issues.
