### ISSUE TITLE
404 SORRY, PAGE NOT FOUND in Magento 1.7.0.2

### ISSUE THREAD

**Issue by lvillarino** [aschroder/Magento-SMTP-Pro-Email-Extension#119]
Hi:

I install the extension and it's work find. We can send emails.

The only problem is the "Email Log" section don't work, we are receiving a 404 error when we try to visit the page, this the url that the extension generate

http://v2.site.com/index.php/smtppro/log/index/key/02366018ee74f7364e3faf99344e5271/

Thanks.

**Comment by dfsdouglas** [comment]
Same issue, but only appeared after SUPEE-5994 security patch installation.
On Magento CE 1.8.0.

**Comment by aschroder** [comment]
merged fixed in next release
