### ISSUE TITLE
"Error 5.1.2: The address specified is not a valid RFC-5321 address" with Google Apps

### ISSUE THREAD

**Issue by philspbr** [aschroder/Magento-SMTP-Pro-Email-Extension#132]
I installed the plugin today and the test run and email are working fine (using Google SMTP), but the transactional emails are not getting delivered. Exception.log says:

exception 'Zend_Mail_Protocol_Exception' with message '5.1.2 The address specified is not a valid RFC-5321 address. k199sm5254091ioe.9 - gsmtp
' in /var/www/html/lib/Zend/Mail/Protocol/Abstract.php:431

The email addresses are correct. Any idea how to fix this?

**Comment by aschroder** [comment]
That 5.1.2 prefix means it’s a message coming back from your smtp server.
The server is telling you the address you are sending from/to is not valid.
“5.1.2 The address specified is not a valid RFC-5321 address”

triple check you have a valid address and if you are certain you do, try
testing with a different outbound email service - thought I highly doubt
gsmtp is wrong here - if that’s a reference to google’s smtp server.

**Comment by philspbr** [comment]
I will try with sendgrid and report back. I think the problem is with Google's SMTP, I saw that a couple of other user have the same problem since a few days:
https://productforums.google.com/forum/#!msg/gmail/2tK2fR7yW-k/cCtV-xynlNsJ

**Comment by aschroder** [comment]
That’s strange - maybe keep an eye on that thread over the next few days -
but I’m not sure this is an SMTP pro issue at this stage.

**Comment by philspbr** [comment]
Just tested SMTP Pro with sendgrid and it's working fine. I will stay with them for now and keep an eye on that thread in the Google Forums.

**Comment by AlexNevskyV** [comment]
Today, i have issue like this.
Check magento store setting in System->Configuration->Sales->Sales Emails. In main layout check fields "Send Order Email Copy To" if this have more then one email (one@example.com, two@eample.com and etc) and "Send Order Email Copy Method" is "Bcc" - try change "Send Order Email Copy Method" to "Separate Email".
This solution helped me and now magento emails sending working fine via SMTP pro with Google Apps without any errors.
