### ISSUE TITLE
Email functionality not working

### ISSUE THREAD

**Issue by ranjitnadar** [aschroder/Magento-SMTP-Pro-Email-Extension#138]
Hi 
i installed SMTP Pro Email Extension followed all steps mentioned in doc, when i test email using smtp pro its working, When any order or new registration email not working

![cron_conf](https://cloud.githubusercontent.com/assets/3095820/11335690/64bc6f06-9204-11e5-90f2-7231b559b944.JPG)
My cron job settings 

if i changes in cronjob settings let me know 

Thanks

**Comment by sandermangel** [comment]
@ranjitnadar  this issue has been open for a while. Please reopen the issue if the problem persists
