### ISSUE TITLE
SMTP Pro is not being used for all emails

### ISSUE THREAD

**Issue by jsasitorn** [aschroder/Magento-SMTP-Pro-Email-Extension#140]
I've setup and testing SMTP Pro to send email confirmations. It is working well.

However, the default magento SMTP code is still being used to send forgot password emails and other emails as well. I'm running Magento 1.9.2.1

**Comment by gfxguru** [comment]
and comments on order are not sent with extension, actually I still can't get this extension to work

**Comment by sandermangel** [comment]
This issue has been open for over 3 years. Closing it, if it's still relevant and reproducible please open a new issue
