### ISSUE TITLE
Exception message was: Could not open socket

### ISSUE THREAD

**Issue by ziyaindia** [aschroder/Magento-SMTP-Pro-Email-Extension#143]
Hello Sir,

I am getting following error on self test:

SMTP Pro Self Test Results
Sending test email to your contact form address: ziya.khan@maggcom.com from: ziya.khan@maggcom.com. Unable to send test email.
Exception message was: Could not open socket
Please check the user guide for frequent error messages and their solutions.
Default templates exist.
Email communications are enabled.

Testing failed, please review the reported problems and if you need further help visit the support page or contact me via support@aschroder.com for support.

Thanks,
Ziya

**Comment by aschroder** [comment]
check with your web host or server admin, likely the outbound
port/connection is being blocked.
