### ISSUE TITLE
Order Confirmation emails are not sent all other emails are ok

### ISSUE THREAD

**Issue by milosbaran** [aschroder/Magento-SMTP-Pro-Email-Extension#144]
Hi,

I have Magento 1.9.2.2.
The only issue I'm having is with order confirmations not being sent when order is placed. 
When triggered manually from admin email is sent and visible in log. 
All other emails are being sent without any issues. (New account, new password, contact form, add comment). 

I have changed the settings so magento queue is bypassed.

Thanks 
Milos

**Comment by aschroder** [comment]
if you’re bypassing the queue and only the order emails are not sending,
then you’ll need more debugging to identify the issue - enable logging,
turn on debug logging setting and see if you get any useful output, if not,
you’ll likely need to trace through the actual email sending routine in
core magento to find out why it’s not sending.

**Comment by pcdubbya** [comment]
I have this same issue, Milos, were you able to get it figured out? Contact Form is fine, but confirmation of sales emails don't send. 
Also, enabling the debug logging for me didn't work. No dir created on server for me to view the log.

Test settings show they are fine and sends me a test email when I test it.

**Comment by milosbaran** [comment]
Hi pcdubbya,

yes I did figure it out. I was plain stupid. Order hasn't received payment confirmation so email was not triggered. I only figured it out when I tested PayPal and everything worked without a single issue.
I'm using Adyen payment gateway that requires any form of notification before sending email.
