### ISSUE TITLE
Wrong subject coding

### ISSUE THREAD

**Issue by langowskiadam** [aschroder/Magento-SMTP-Pro-Email-Extension#145]
Hello, 
I recieve wrong subject in mailbox and mail logs: Nowe zam&oacute;wienie # 100000381 should be Nowe zamówienie # 100000381.

How can I repair?

Kind regards

**Comment by sandermangel** [comment]
This issue is related to the Magento email templates, not the module itself. Closing this issue.
If there is any update to this issue do let us know
