### ISSUE TITLE
Save config is giving internal server error

### ISSUE THREAD

**Issue by Lovnish** [aschroder/Magento-SMTP-Pro-Email-Extension#148]
hi..

i have succesfully installed extension.When i click on save config while editing smt credentials for custom smtp its giving internal server error.

Please help me as soon as posible.

Regards

Lovnish

**Comment by MichielTG** [comment]
I got the same issue with magento 1.9.1.0

**Comment by aschroder** [comment]
check your apache logs and/or exception logs to find out what the actual
error is, then let me know?
