### ISSUE TITLE
Mage_Core_Model_Email_Queue not found

### ISSUE THREAD

**Issue by hans2103** [aschroder/Magento-SMTP-Pro-Email-Extension#150]
I get a fatal error while using Magento SMTP Pro Email Extension

```
Fatal error: Class 'Mage_Core_Model_Email_Queue' not found in /home/verzorgi/public_html/.modman/Magento-SMTP-Pro-Email-Extension/app/code/local/Aschroder/SMTPPro/Model/Email/Queue.php on line 10
```

When I `grep` on 'Mage_Core_Model_Email_Queue' I can't find it neither.

**Comment by aschroder** [comment]
what version of magento are you running? older versions have no queue, but
with no queue, there'd be normally no reason they would invoke either
Aschroder/SMTPPro/Model/Email/Queue.php or Mage_Core_Model_Email_Queue.

**Comment by Mic2005** [comment]
1.7.0.2 CE

**Comment by aschroder** [comment]
You'd probably be safe to simply delete that file - though it's not clear
to me why it's being invoked... do you have a stack trace from that
exception?

**Comment by Mic2005** [comment]
I only see this error in the Magento Config - Amasty Extensions & Notifications - Troubleshooter tab (Models):
![image](https://cloud.githubusercontent.com/assets/11639487/13112065/94d62722-d589-11e5-9f99-5dcfa9089c34.png)
I think @hans2103 can't produce/find a stack trace.
