### ISSUE TITLE
TO Column empty in log

### ISSUE THREAD

**Issue by shirtsofholl** [aschroder/Magento-SMTP-Pro-Email-Extension#155]
Hi, we use Magento 1.9.2.4 on php7 and see that the TO column is empty in mail log

![image](https://cloud.githubusercontent.com/assets/11224809/14087232/3304d150-f529-11e5-8398-c40fcdb2c14e.png)

**Comment by hanuman42** [comment]
same here Magento 1.9.2.4 php 5.5
TO column is empty.

anybody any directions?

**Comment by sandermangel** [comment]
If this issue is still up to date please reopen it
