### ISSUE TITLE
Emails still going in queue and now sending

### ISSUE THREAD

**Issue by akent64** [aschroder/Magento-SMTP-Pro-Email-Extension#156]
I have set the Queue Usage = Never but emails are still going into core_email_queue and core_email_queue_recipients and emails not sending.

I have also installer AOE scheduler to test the cron but that was not working either.

I have set the smtp in settings on the Default Config but it doesn't give me option to set these on a store level (We have 2 stores running from 1 Magento admin)

Any help would be greatly appreciated!

Many thanks

Andrew

**Comment by sandermangel** [comment]
This is an older issue, if this is still relevant please reopen the issue with any extra information you might have.
