### ISSUE TITLE
Aschroder_SMTPPro_Model_Email outdated rewrite , wrong encoding on e-mails 

### ISSUE THREAD

**Issue by speedupmate** [aschroder/Magento-SMTP-Pro-Email-Extension#157]
the file extended by Aschroder_SMTPPro_Model_Email defines encoding 

new Zend_Email('utf-8'); 

but this class is missing this , so e-mails are sent out as iso-wahtever-fails-in-your-inbox worth to revisit and diff against the file it extends

**Comment by sandermangel** [comment]
This is an older issue, if this is still relevant please reopen the issue with any extra information you might have.
