### ISSUE TITLE
Not sending on https & using the queue

### ISSUE THREAD

**Issue by sam327** [aschroder/Magento-SMTP-Pro-Email-Extension#159]
I've got a store on Magento 1.9.1.0 - and we're using this plugin to send out via sendgrid.

In the default configuration, emails are getting sent out via the local sendmail.php instead of using the plugin. 

If I change the queue setting to "Never" so that it immediately sends emails, the order confirmations go out via sendgrid. 

Oddly, in my development environment it sends everything correctly. It's just in my production environment. The difference between them is that production is https all the time and has some caching (like redis), and dev is just http. But this may be a red herring.

**Comment by sandermangel** [comment]
This is an older issue, if this is still relevant please reopen the issue with any extra information you might have.
