### ISSUE TITLE
How to install in Magento 2.04?

### ISSUE THREAD

**Issue by 9SL9** [aschroder/Magento-SMTP-Pro-Email-Extension#160]
I've tried to follow the extension using these instructions but it doesn't appear to work.

http://www.aschroder.com/2010/05/installing-a-magento-extension-manually-via-ftp-or-ssh/

I've also read that magento connect is not exactly stable for magento 2.x. I myself can't even sync my purchases successfully. So I'm hoping you can point me to or provide some installation instructions for version 2.04.

Thanks!

**Comment by diglin** [comment]
It's a Magento 1.x module
