### ISSUE TITLE
Exception message was: Connection refused

### ISSUE THREAD

**Issue by atomiclife** [aschroder/Magento-SMTP-Pro-Email-Extension#163]
SMTP Pro Self Test Results
Sending test email to your contact form address: hello@example.com from: smile.akarsh@gmail.com. Unable to send test email.
Exception message was: Connection refused
Please check the user guide for frequent error messages and their solutions.
Default templates exist.
Email communications are enabled.

I even tried changing the smtp server, but the same error. Please help

![configuration system magento admin](https://cloud.githubusercontent.com/assets/18416608/14454687/6a469324-00b9-11e6-8c3f-b5649fb4c78c.jpg)

**Comment by GustavoSartori** [comment]
Same problem here!
I have just tryed test using my SendGrid account and the problem is the same.

**Comment by GustavoSartori** [comment]
I'm still trying to solve this. I'm trying with SendGrid account, bit even if I use gmail or my own server the messege is the same.

Here's my log:
`2016-04-26T03:05:36+00:00 DEBUG (7): Running SMTP Pro Self Test
2016-04-26T03:05:36+00:00 DEBUG (7): Checking config re-writes have not clashed.
2016-04-26T03:05:36+00:00 DEBUG (7): Using Sendgrid Transport.
2016-04-26T03:05:36+00:00 DEBUG (7): Skipping raw connection test for non-SMTP options.
2016-04-26T03:05:36+00:00 DEBUG (7): Actual email sending test...
2016-04-26T03:05:36+00:00 DEBUG (7): Zend_Mail Object
(
    [_charset:protected] => iso-8859-1
    [_headers:protected] => Array
        (
            [To] => Array
                (
                    [0] => [edited]@[edited].com.br
                    [append] => 1
                )

            [From] => Array
                (
                    [0] => [edited]@[edited].com.br
                    [append] => 1
                )

            [Subject] => Array
                (
                    [0] => Test Email From SMTP Pro Magento Extension
                )

        )

    [_headerEncoding:protected] => quoted-printable
    [_from:protected] => [edited]@[edited].com.br
    [_to:protected] => Array
        (
            [0] => [edited]@[edited].com.br
        )

    [_recipients:protected] => Array
        (
            [[edited]@[edited].com.br] => 1
        )

    [_replyTo:protected] => 
    [_returnPath:protected] => 
    [_subject:protected] => Test Email From SMTP Pro Magento Extension
    [_date:protected] => 
    [_messageId:protected] => 
    [_bodyText:protected] => Zend_Mime_Part Object
        (
            [type] => text/plain
            [encoding] => quoted-printable
            [id] => 
            [disposition] => inline
            [filename] => 
            [description] => 
            [charset] => iso-8859-1
            [boundary] => 
            [location] => 
            [language] => 
            [_content:protected] => Hi,

This is a Test Email from your Magento Store. If you are seeing this email then your SMTPPro settings are correct! 

For more information about this extension and tips for using it please visit magesmtppro.com or contact me, support@aschroder.com.

Regards,
Ashley
            [_isStream:protected] => 
        )

    [_bodyHtml:protected] => 
    [_mimeBoundary:protected] => 
    [_type:protected] => 
    [hasAttachments] => 
    [_parts:protected] => Array
        (
        )

    [_mime:protected] => 
)

2016-04-26T03:05:36+00:00 DEBUG (7): Using Sendgrid Transport.
2016-04-26T03:05:38+00:00 DEBUG (7): Test email was not sent successfully: Connection refused
2016-04-26T03:05:38+00:00 DEBUG (7): See exception log for more details.
2016-04-26T03:05:38+00:00 DEBUG (7): Checking that a template exists for the default locale and that email communications are enabled...
2016-04-26T03:05:38+00:00 DEBUG (7): Default templates exist and email communications are enabled.
2016-04-26T03:05:38+00:00 DEBUG (7): Checking that tables are created...
2016-04-26T03:05:38+00:00 DEBUG (7): Required database tables exist.
2016-04-26T03:05:38+00:00 DEBUG (7): Completo
` 

I'm using Magento 1.9.2.4 at GoDaddy shared host.

**Comment by Chouhdary** [comment]
Did you manage to find any solution for this as i seem to have end up on same and cannot find any resolution for that . I am on godaddy shared hosting as well .@Gustavo

**Comment by atomiclife** [comment]
no solutions yet..

*Regards,*

*Akarshkumar B G*
Graphic & Web Designer

**Comment by QiuLihua83** [comment]
I get this result too.
I tried different smtp services but get the same result "connection refused.".
Help me please.

**Comment by Chouhdary** [comment]
Its an issue with restriction by hosting company. Godaddy will not make
changes for you as we did have challenges with them.

only option unfortunately is to change your hosting provider.

**Comment by anhuy1989** [comment]
Please use the command below to check the status of your port:
openssl s_client -connect smtp.gmail.com:587 -starttls smtp

I think some configurations from iptables or firewalld went wrong.

Check this one for more details:
https://serverfault.com/questions/765286/connect-to-smtp-gmail-connection-refused

**Comment by apzeiro** [comment]
Same issue here.
@anhuy1989  I tried this command and I received a time out.

**Comment by howie** [comment]
My error message is 

SMTP Pro Self Test Results
Sending test email to your contact form address: xxx from: xxx. Unable to send test email.
Exception message was: **Could not open socket**
Please check the user guide for frequent error messages and their solutions.
Default templates exist.
Email communications are enabled.
Required database tables exist.
Testing failed, please review the reported problems and if you need further help visit the support page or contact me via support@aschroder.com for support.

**Comment by sandermangel** [comment]
@howie please include details of what kind of SMTP server you use and include details of the steps you followed in the user guide and output of openssl in a new issue

**Comment by sandermangel** [comment]
@apzeiro @andylhqiu if you get a timeout it means an issue with the server. most likely its restricted by the hosting company

**Comment by howie** [comment]
Hi @sandermangel   
I use smtp.gmail.com. 
The strange thing is the email for order is fine. But registration and forget password and  self test are all fail.  
exception 'Zend_Mail_Protocol_Exception' with message 'Could not open socket' in /opt/magento/htdocs/lib/Zend/Mail/Protocol/Abstract.php:277
Stack trace:
#0 /opt/magento/htdocs/lib/Zend/Mail/Protocol/Smtp.php(167): Zend_Mail_Protocol_Abstract->_connect('tcp://smtp.gmai...')
#1 /opt/magento/htdocs/lib/Zend/Mail/Transport/Smtp.php(199): Zend_Mail_Protocol_Smtp->connect()
#2 /opt/magento/htdocs/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#3 /opt/magento/htdocs/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#4 /opt/magento/htdocs/app/code/local/Aschroder/SMTPPro/controllers/Smtp/TestController.php(136): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
#5 /opt/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aschroder_SMTPPro_Smtp_TestController->indexAction()
#6 /opt/magento/htdocs/app/code/local/Mage/Core/Controller/Varien/Router/Standard.php(252): Mage_Core_Controller_Varien_Action->dispatch('index')
#7 /opt/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /opt/magento/htdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#9 /opt/magento/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /opt/magento/htdocs/index.php(85): Mage::run('shop_ausen_com_...', 'website')

**Comment by sandermangel** [comment]
Hi @howie this means the server is blocking the request. please contact your hosting provider
