### ISSUE TITLE
Configuration can't be set on website level even though config options are on website level.

### ISSUE THREAD

**Issue by kega-jira** [aschroder/Magento-SMTP-Pro-Email-Extension#164]
We want to use different mailserver per website in Magento. So we thought to setup the config options for the server on website level (behind the values it says website, so it's expected to be able to set this on this level.

When I change the scope to the website level, there's no config option anymore to choose SMTP Pro config options in the Magento sidebar? Anyone a solution for this problem?
We really need to have each website to have it's own mailserver while the companies need to split costs so they each pay for their own server. So one server for all is not an option.

Help?

**Comment by pleaseremove** [comment]
Hi, I also have exactly the same issue and have yet to find a solution. Will update if I work it out, but just wanted to say I am someone else with the same issue

**Comment by pleaseremove** [comment]
For ref @kega-jira my fix for this was to update /app/code/local/Aschroder/SMTPPro/etc/system.xml and I changed the 0's on lines 8 and 20 both to 1's.

So in other words allowing show_in_website for both the global tab and for the section. Then you just have to make sure you selected the service from global and fill in the settings on the website level for those.

Hope that helps

**Comment by raulsinapsis** [comment]
You can try this https://github.com/aschroder/Magento-SMTP-Pro-Email-Extension/pull/259

**Comment by sandermangel** [comment]
Different scopes of configuration is not supported in the module. Closing this issue.
Feel free to open a feature request for this
