### ISSUE TITLE
I am using Magento 1.9.0

### ISSUE THREAD

**Issue by sankharay** [aschroder/Magento-SMTP-Pro-Email-Extension#165]
i conf. Custom SMTP. Which works for Test but not working for transactional emails. ( i test locally & on Linux Ubuntu Servers )

i tried Custom SMTP & Amazon SES in both transactional emails not working.

when i use Amazon SES then i am getting error:

Check the date and time on your server is set correctly.
Amazon's servers think your server time is more than 5 minutes different to their time and are rejecting the request.
Default templates exist.
Email communications are enabled.

please let me know what's wrong.

**Comment by jshor** [comment]
+1. I'm also having this issue.

**Comment by aschroder** [comment]
The error message is pretty clear, I thought:


*Check the date and time on your server is set correctly.Amazon's servers
think your server time is more than 5 minutes different to their time and
are rejecting the request.*

What have you tried?

**Comment by jshor** [comment]
@aschroder sorry! I'm actually not getting an error. It's just not sending emails for me. I'm moving my comment to #154. By the way - thanks for this great extension!

**Comment by sankharay** [comment]
i am not able to send transaction emails. but when i test email working fine and in Amazon i can see email send. but when i place order & any other things. i am not receiving any kind of email.

MAIN PROBLEM:  extension not sending transaction emails like new order, user registration and more...

**Comment by sandermangel** [comment]
Please reopen this issue and add any relevant information if this item is still relevant
