### ISSUE TITLE
How to add Custom Header in SMTP Pro Email Extention

### ISSUE THREAD

**Issue by snosirov** [aschroder/Magento-SMTP-Pro-Email-Extension#236]
Hello, I want integrate Mandrill SubAccount by adding a Custom Header.
How can I do this and where? 
This is the Code: $mail->addCustomHeader('X-MC-Subaccount', 'IDMandrill');
1. X-MC-Subaccount - Mandrill Custom Header Reference
2. IDMandrill - Mandrill SubAccount ID

Thanks!

**Comment by sandermangel** [comment]
Hi @snosirov  what have you tried so far in terms of adding this?
