### ISSUE TITLE
Google Apps or Gmail error: Unable to connect via TLS

### ISSUE THREAD

**Issue by joell67** [aschroder/Magento-SMTP-Pro-Email-Extension#237]
Magento 1.9.3.4 on shared hosting.

SMTP Pro installed worked great, but suddenly stopped sending transnational emails.
Using **Google Apps or Gmail** connection.

Password is correct and can login to Gmail.

When self tested, received error:
> SMTP Pro Self Test Results
> Sending test email to your contact form address: Support@mysite.com from: Support@mysite.com. Unable to send test email.
> Exception message was: Unable to connect via TLS
> Please check the user guide for frequent error messages and their solutions.
> Default templates exist.
> Email communications are enabled.

[Support page](http://www.aschroder.com/product/smtppro-magento-smtp-email/) suggests having OpenSSL installed:

> Q: Self test is failing with “Exception message was: Unable to connect via TLS”
> A: Check that you have OpenSSL installed for your PHP environment. 

I double checked in php.ini, OpenSSL is installed and enabled. No recent change at all.

> OpenSSL support | enabled
> OpenSSL Library Version | OpenSSL 1.0.2k-fips 26 Jan 2017
> OpenSSL Header Version | OpenSSL 1.0.2k-fips 26 Jan 2017
> Openssl default config | /opt/alt/openssl/etc/pki/tls/openssl.cnf
> 

Any ideas what else could be the culprit?

Rgds

**Comment by sandermangel** [comment]
Hi @joell67 did you try making the connection directly from the command line with telnet for example? This would give an indication whether it is the module or maybe something related to the server setup

**Comment by joell67** [comment]
How do you make a connection directly from cmd line?

**Comment by sandermangel** [comment]
Hi @joell67 , you can try this article: http://smallbusiness.chron.com/connect-gmail-telnet-26966.html

**Comment by sandermangel** [comment]
Hi @joell67 I haven't heard back from you yet. I will close this issue for now
