### ISSUE TITLE
How to send emails other than the contact form?

### ISSUE THREAD

**Issue by adamnicholls85** [aschroder/Magento-SMTP-Pro-Email-Extension#238]
So after reading through a bunch of threads about this plugin it seems like I'm not the only one to have this problem and I can't seem to find a solution to this.  The plugin works fine when sending test e-mails.  It literally doesn't do anything else, every other e-mail sent through Magento is through Magento's default SMTP settings.  How do I configure this to get it to send the order confirmation e-mails? I'm working with Magento version 1.9.3.1 and we're using Google Apps.

**Comment by sandermangel** [comment]
Hi Adam, this could be due to an overwrite conflict. The module needs to overwrite like `core/email` and `core/email_template` to do its work. Modules like Dotmailer and Mailchimp tend to overwrite the same ones. 
Might something like that apply here?

**Comment by adamnicholls85** [comment]
Yup, that seems to be what it is, the test e-mail would get sent despite the conflict but after disabling the extension that was causing the conflict, everything is running smoothly now.  Thanks for the help!

**Comment by sandermangel** [comment]
You are welcome. glad you got it resolved
