### ISSUE TITLE
Sender address rejected: not owned by user name@domain.com | Custom SMTP | Magento 1.9.2.4

### ISSUE THREAD

**Issue by ranjo8192** [aschroder/Magento-SMTP-Pro-Email-Extension#242]
Hi,
I have been using SMTP pro since last 1 month with sendgrid, every thing was working good and all the mails was being delivered . But now I have changed it from sendgrid to custom SMTP. Every things seems to be fine but I have one custom form in my website, from there we are not getting email.

I have checked my exception.log, it says:  **Sender address rejected: not owned by user name@domain.com**

*************************Log******************************
exception 'Zend_Mail_Protocol_Exception' with message '5.7.1 \<email@domain.com>: Sender address rejected: not owned by user email@domain.com
' in /home/username/public_html/lib/Zend/Mail/Protocol/Abstract.php:431
Stack trace:
#0 /home/username/public_html/lib/Zend/Mail/Protocol/Smtp.php(289): Zend_Mail_Protocol_Abstract->_expect(Array, 300)
#1 /home/username/public_html/lib/Zend/Mail/Transport/Smtp.php(211): Zend_Mail_Protocol_Smtp->rcpt('email@domain...')
#2 /home/username/public_html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#3 /home/username/public_html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#4 /home/username/public_html/app/code/local/Aschroder/SMTPPro/Model/Email/Template.php(132): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
#5 /home/username/public_html/app/code/local/Mage/Core/Model/Email/Template.php(508): Aschroder_SMTPPro_Model_Email_Template->send('email@domain...', 'Team OCM', Array)
#6 /home/username/public_html/app/code/local/Tvbocm/RefillOrderForm/controllers/IndexController.php(86): Mage_Core_Model_Email_Template->sendTransactional(30, Array, 'email@domain...', 'Team OCM', Array)
#7 /home/username/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Tvbocm_RefillOrderForm_IndexController->postAction()
#8 /home/username/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('post')
#9 /home/username/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /home/username/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#11 /home/username/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /home/username/public_html/index.php(90): Mage::run('', 'store')
#13 {main}
**************************************

My settings for custom SMTP are:

Username: name@domain.com
password : **********
host         : smtp.domain.com
port         :25
SSL Security: no

Can you please let me know how can I fix it or How to use custom SMTP for sending emails?

Thanks in advance!

**Comment by sandermangel** [comment]
This does not seem to be something related to the module, but to configuration on server level: https://serverfault.com/questions/637726/sender-address-rejected-not-owned-by-user-in-postfix

**Comment by ranjo8192** [comment]
Thanks! @sandermangel
