### ISSUE TITLE
SMTP: Unable to connect via TLS (with TLSv1.0 disabled?)

### ISSUE THREAD

**Issue by davidpeoples** [aschroder/Magento-SMTP-Pro-Email-Extension#248]
Our Magento site using this plugin is no longer able to send outbound emails. According to the email log the failure started on the date the server company disabled TLSv1.0 for PCI compliance. I have tested connecting to port 587 using telnet and the connection works. ("telnet localhost 587" from an SSH login to that server returns the proper ESMTP prompt.)

Is this extension compatible with TLSv1.1 or TLSv1.2? Both of those are still enabled on this server. We are using version 2.0.7 of the extension.

**Comment by hackzilla** [comment]
We had this issue.

Turns out we are 1.12 of the Zend Framework, and it seems to be allow any version of TLS.
Now I don't recommend doing this, but what we did was edit ```Zend/Mail/Protocol/Smtp.php```

Replace ```STREAM_CRYPTO_METHOD_TLS_CLIENT``` with ```STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT ```.

This forces it to try TLS 1.2

**Comment by bluec** [comment]
Grim. I guess we can override that lib in the local codepool instead of modifying the core file...

**Comment by sandermangel** [comment]
@hackzilla thank you for sharing the solution

**Comment by bluec** [comment]
Just to confirm, the better way to do this is to copy `lib/Zend/Mail/Protocol/Smtp.php` to `app/code/local/Zend/Mail/Protocol/Smtp.php` and then make the change in there. This will ensure it is not overwritten by future Magento updates and also avoids core code changes.

For maximum compatibility I would recommend changing `STREAM_CRYPTO_METHOD_TLS_CLIENT` to `STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT | STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT`, but if you know your server supports TLS1.2 then @hackzilla's suggestion is fine.
