### ISSUE TITLE
Error 500 When Saving Password

### ISSUE THREAD

**Issue by mayardmc** [aschroder/Magento-SMTP-Pro-Email-Extension#251]
Hello!
I'm having trouble configuring the module.
When you enter a password to set up a custom smtp, or enter login and password for the sendgrid, the page returns the 500 error and does not save the password. can you help me?

**Comment by sandermangel** [comment]
Hi @mayardmc please check your magento and apache/nginx error logs for the exact error it throws when returning a 500 status.

**Comment by mayardmc** [comment]
Hi @sandermangel ! Thanks for answering!

in the magento logs, there is no corresponding related error. In the apache error logs I also can not find...
In the Apache ACCESS LOGS I can find the following lines:

201.182.70.2 - - [31/Jul/2018:09:05:44 -0300] "GET /index.php/admin/system_config/edit/section/smtppro/key/ff4c688210e8fb087888da8859ed515b/ HTTP/1.1" 200 22464 "http://www.sayro.com.br/index.php/admin/system_config/edit/section/dev/key/ff4c688210e8fb087888da8859ed515b/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
201.182.70.2 - - [31/Jul/2018:09:05:56 -0300] "POST /index.php/admin/system_config/save/section/smtppro/key/ae88ba5b2a6c9fc17aae7efefb8213a1/ HTTP/1.1" 500 - "http://www.sayro.com.br/index.php/admin/system_config/edit/section/smtppro/key/ff4c688210e8fb087888da8859ed515b/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

regards,

Mayard

**Comment by mayardmc** [comment]
as it can be seen, the installation of mcrypt was lacking.
