### ISSUE TITLE
Order Confirmation Mails not being sent

### ISSUE THREAD

**Issue by datsoli** [aschroder/Magento-SMTP-Pro-Email-Extension#252]
I have the issue that some order confirmation e-mails aren't being sent.
Seems to me that all orders that are paid by credit card aren't working while all others are fine.
I already checked with the extension we are using for credit card payments but there doesn't seem to be an issue, the sendNewOrderEmail() method is called properly.

Also there is an entry in the aschroder_smtppro.log for the missing mail but it's not being sent out to the customer, and it doesn't appear in the SMTPPro Log in the Backend. I can't find any error messages too.
The queue tables in the database are empty too.
All other e-mails are being sent so I don't think there's a problem with sending emails in general or with the cron jobs.

Any ideas what might be the problem here?

Edit:
What I just noticed, the timestamp in the Log is completely wrong for the mail that is missing:

> 2018-07-31T09:38:49+00:00 DEBUG (7): Using Custom SMTP Transport.
2018-07-31T09:53:03+00:00 DEBUG (7): Zend_Mail Object

09:53 (the 2nd line) is the correct time so the first line should be about the same but instead shows 09:38 which is definitely wrong. The order was made at about 11:50 and the timestamp in the log is 2 hours behind, so should show 09:50 +/- but can't possibly be 09:38

may this be somehow related to the problem?

**Comment by extremeskillz** [comment]
Same here I'm getting Exception message was: Unable to connect via TLS. 

Ubuntu 16.04LTS, Magento 1.9.3 on LAMP Stack. PHP5.6

**Comment by sandermangel** [comment]
Hi @datsoli the log times is set by the server. your hosting provider should be able to change that.
In regards to the email not being sent, I'm afraid we'll need more information.
It sounds like maybe a rewrite conflict with another module
