### ISSUE TITLE
Why email is going to spam when using Custom SMTP ?

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [aschroder/Magento-SMTP-Pro-Email-Extension#254]
We are using this extension http://www.aschroder.com/product/smtppro-magento-smtp-email/

our mail is going to customer spam instead of inbox when using custom SMTP

**Comment by sandermangel** [comment]
Hi @sumeetmobiwebtech, very sorry to hear that.
however, this is not due to a technical issue with the module. Most likely it's either the content of the mail, a penalty on the customers domain or incorrect settings in the email records on the DNS for verfication
