### ISSUE TITLE
Exception message was: Unable to connect via TLS inspite of OpenSSL installed and PHP 5.6

### ISSUE THREAD

**Issue by neps-in** [aschroder/Magento-SMTP-Pro-Email-Extension#260]
Self test is failing with "Exception message was: Unable to connect via TLS" A: Check that you have OpenSSL installed for your PHP environment. What is the resolution ?

I have checked OpenSSL is enabled, this is what I get in phpinfo()

OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 1.0.1j 15 Oct 2014
OpenSSL Header Version	OpenSSL 1.0.1h 5 Jun 2014

Also I followed this issue #248 
https://github.com/aschroder/Magento-SMTP-Pro-Email-Extension/issues/248

Also this piece of code is also present
https://magento.stackexchange.com/questions/232231/smtp-pro-plugin-tls-1-1-exception-message-was-unable-to-connect-via-tls-s

What should i do now. I am on Mountain lion

**Comment by sandermangel** [comment]
HI, I'm afraid PHP5.6 is no longer supported as the PHP version itself is end of life
