### ISSUE TITLE
Error when using hotmail (Custom SMTP)

### ISSUE THREAD

**Issue by carlis8** [aschroder/Magento-SMTP-Pro-Email-Extension#262]
Hello all,
I have this issue in my exception.log . I am using the extension with hotmail

2019-04-04T10:00:03+00:00 ERR (3): 
exception 'Zend_Mail_Protocol_Exception' with message '5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 16.55847:C81C0000, 17.43559:0000000094000000000000000000000000000000, 20.52176:140FEB86000010100A00F480, 20.50032:140FEB86701710100A00F580, 0.35180:B4050000, 255.23226:0A00F680, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A000000, 16.55847:C4000000, 17.43559:00000000A0010000000000000100000000000000, 20.52176:140FEB860000101003000136, 20.50032:140FEB86701710100A00DA36, 0.35180:44000000, 255.23226:4800D13D, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:0A003A66, 4.21921:DC040000, 255.27962:FA000000, 255.1494:64000000, 0.38698:01040480, 0.37692:08000100, 0.44092:08000100, 0.41232:08000100, 0.60208:08000100, 0.37136:08000100, 0.34608:08000100, 0.55056:08000100, 0.42768:08000100, 0.56112:3A313135, 0.52807:342D6238, 4.33016:DC040000, 7.40748:010000000000010B31326131, 7.57132:000000000000000000000000, 1.63016:' in /var/www/xxx/xxx/xxx/lib/Zend/Mail/Protocol/Abstract.php:431
Stack trace:
#0 /var/www/xxx/xxx/xxx/lib/Zend/Mail/Protocol/Smtp.php(324): Zend_Mail_Protocol_Abstract->_expect(250, 600)
#1 /var/www/xxx/xxx/xxx/lib/Zend/Mail/Transport/Smtp.php(215): Zend_Mail_Protocol_Smtp->data('To: =?utf-8?B?Q...')
#2 /var/www/xxx/xxx/xxx/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#3 /var/www/xxx/xxx/xxx/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#4 /var/www/xxx/xxx/xxx/app/code/local/Aschroder/SMTPPro/Model/Email/Queue.php(99): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
#5 [internal function]: Aschroder_SMTPPro_Model_Email_Queue->send(Object(Mage_Cron_Model_Schedule))
#6 /var/www/xxx/xxx/xxx/app/code/core/Mage/Cron/Model/Observer.php(326): call_user_func_array(Array, Array)
#7 /var/www/xxx/xxx/xxx/app/code/core/Mage/Cron/Model/Observer.php(72): Mage_Cron_Model_Observer->_processJob(Object(Mage_Cron_Model_Schedule), Object(Mage_Core_Model_Config_Element))
#8 /var/www/xxx/xxx/xxx/app/code/core/Mage/Core/Model/App.php(1358): Mage_Cron_Model_Observer->dispatch(Object(Varien_Event_Observer))
#9 /var/www/xxx/xxx/xxx/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Cron_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#10 /var/www/xxx/xxx/xxx/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#11 /var/www/xxx/xxx/xxx/cron.php(78): Mage::dispatchEvent('default')
#12 {main}

**Comment by sandermangel** [comment]
Hi, this error comes from hotmail, you'll have to find out with them what is going on.
unfortunately I have no idea on how the extension works with hotmail as smtp server.

**Comment by carlis8** [comment]
Hello @sandermangel, thanks for your fast response.
I understand what you say, but, I have been researching a bit, and I found that some people faced this problem before (out of magento and this extension) and it is a problem with the email set up as sender (It can be read in the exception itself). Is there any way in the extension to change the email set up as sender?
