### ISSUE TITLE
Error 404 when running test

### ISSUE THREAD

**Issue by ghost** [aschroder/Magento-SMTP-Pro-Email-Extension#36]
Running Magento ver. 1.8.1.0 and just installed ASchroder_SMTPPro 2.0.2 (stable) still facing the 404 error when running a test for Gmail account.

All works fine on the same server with another account with ASchroder_SMTPPro  1.4.3 (stable) on Magento ver. 1.8.1.0 - with 'usual erros' - but it does work: copies of sent item appear in GMail.

Note: No extra extension like MailChimp etc installed.

**Comment by testusernetwork1** [comment]
we also get the same 404 error, we using Magento ver. 1.7.0.2 and Aschroder_SMTPPro 1.4.3
and using SMTP settings 
if we click "Run self test" button we get 404 error.

"Add Store Code to Urls" is Disabled in our system.

System-> Tools -> Email Log its also get 404 error.

how can we find the error. please help to fix the issue.

Thanks.
