### ISSUE TITLE
'This letter cannot be sent.' Error

### ISSUE THREAD

**Issue by Penina** [aschroder/Magento-SMTP-Pro-Email-Extension#38]
I have your latest version of SMTP Pro downloaded. I recently uninstalled MageMonkey because it was interfering with transactional emails. Now, when I run a self test, everything works fine. However, when a new customer registers, they no longer get sent the confirmation email. (I had no problems with this before my initial download of MageMonkey.)

In exception.log I get:

exception 'Exception' with message 'This letter cannot be sent.' in /var/www/app/code/local/Aschroder/SMTPPro/Model/Email/Template.php:40
Stack trace:
#0 /var/www/app/code/core/Mage/Core/Model/Email/Template.php(506): Aschroder_SMTPPro_Model_Email_Template->send('pgilbert@nutisp...', 'Penina Gilbert', Array)
#1 /var/www/app/code/local/MagePsycho/Loginredirectpro/Model/Customer.php(51): Mage_Core_Model_Email_Template->sendTransactional('1', 'customer_regist...', 'pgilbert@nutisp...', 'Penina Gilbert', Array)
#2 /var/www/app/code/local/MagePsycho/Loginredirectpro/controllers/AccountController.php(71): MagePsycho_Loginredirectpro_Model_Customer->sendNewAccountEmail('registered')
#3 /var/www/app/code/core/Mage/Customer/controllers/AccountController.php(337): MagePsycho_Loginredirectpro_AccountController->_welcomeCustomer(Object(MagePsycho_Loginredirectpro_Model_Customer))
#4 /var/www/app/code/core/Mage/Customer/controllers/AccountController.php(288): Mage_Customer_AccountController->_successProcessRegistration(Object(MagePsycho_Loginredirectpro_Model_Customer))
#5 /var/www/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createPostAction()
#6 /var/www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('createpost')
#7 /var/www/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /var/www/index.php(87): Mage::run('', 'store')
#11 {main}

In aschroder_smtppro.log I get:

DEBUG (7): Using Custom SMTP Transport.
DEBUG (7): Email is not valid for sending, this is a core error that often means there's a problem with your email templates.

And in Magento's backend on the Manage Customers page I get:

An error occured while rewriting "monkey/adminhtml_customer_edit_tab_memberactivity" : "The original class "Mage_Monkey_Block_Adminhtml_Customer_Edit_Tab_Memberactivity" does not exist" (rewriter: "eval")

**Comment by farazWebDev** [comment]
I am also getting same 

2016-03-11T09:23:15+00:00 ERR (3): 
exception 'Exception' with message 'This letter cannot be sent.' in /var/www/html/app/code/local/Aschroder/SMTPPro/Model/Email/Template.php:40
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Email/Template.php(507): Aschroder_SMTPPro_Model_Email_Template->send('faraz@nine00.co...', NULL, Array)
#1 /var/www/html/app/code/core/Mage/Newsletter/Model/Subscriber.php(523): Mage_Core_Model_Email_Template->sendTransactional('newsletter_subs...', 'support', 'faraz@nine00.co...', NULL, Array)
#2 /var/www/html/app/code/core/Mage/Newsletter/Model/Subscriber.php(356): Mage_Newsletter_Model_Subscriber->sendConfirmationRequestEmail()
#3 /var/www/html/app/code/core/Mage/Newsletter/controllers/SubscriberController.php(64): Mage_Newsletter_Model_Subscriber->subscribe('faraz@nine00.co...')
#4 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Newsletter_SubscriberController->newAction()
#5 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('new')
#6 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/html/index.php(87): Mage::run('', 'store')
#10 {main}


and think no one can help us, even the extension developer also, even they don't know why this cause.
everyone saying template issue, i just put a <p>text</p> to test nothing happen, except this error. lol now what is template ???.

**Comment by e-retailer** [comment]
I've got the same issue,

exception 'Exception' with message 'This letter cannot be sent.' in /home/users/xxx/xxx.nl/app/code/local/Aschroder/SMTPPro/Model/Email/Template.php:40
Stack trace:
#0 /home/users/xxx/xxx.nl/app/code/core/Mage/Core/Model/Email/Template.php(508): Aschroder_SMTPPro_Model_Email_Template->send(Array, NULL, Array)
#1 /home/users/xxx/xxx.nl/app/code/community/Pixlogix/Flexibleforms/controllers/IndexController.php(562): Mage_Core_Model_Email_Template->sendTransactional('pixlogix_flexib...', Array, Array, NULL, Array, '8')
#2 /home/users/xxx/xxx.nl/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Pixlogix_Flexibleforms_IndexController->submitAction()
#3 /home/users/xxx/xxx.nl/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('submit')
#4 /home/users/xxx/xxx.nl/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /home/users/xxx/xxx.nl/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#6 /home/users/xxx/xxx.nl/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /home/users/xxx/xxx.nl/index.php(112): Mage::run('rfnl', 'store')


How can i solve this problem?

**Comment by virik** [comment]
Got the same issue here. Did you get it solved, if so, how?

**Comment by aschroder** [comment]
it's a core error, means there's probably something wrong with your
templates

**Comment by sandermangel** [comment]
@Penina  this issue has been open for quite some time. I will close it but if you have any more information or feedback please open it back up

**Comment by Jongosi** [comment]
I've recently encountered this issue on a legacy site running this plugin. The issue seems to be due to special characters in either the customer name or the shipping and/or billing address.

For example, the umlaut in Marché will trigger this error, since Magento email templates in version 1 do not handle special character encoding.
