### ISSUE TITLE
Errors if config has not been saved

### ISSUE THREAD

**Issue by will-b** [aschroder/Magento-SMTP-Pro-Email-Extension#39]
This only occurs when the config for the module has not been saved. 

Fatal error: Call to a member function getTransport() on a non-object in app/code/local/Aschroder/SMTPPro/Helper/Data.php on line 21

'Exception' with message 'Warning: include(Aschroder/SMTPPro/Model/Transports/0.php): failed to open stream: No such file or directory  in .../lib/Varien/Autoload.php on line 93' in .../app/code/core/Mage/Core/functions.php:245

should `<option>0</option>` be `<option>disabled</option>` in config.xml ?

**Comment by sandermangel** [comment]
Closing this issue as it refers to an earlier version of the module and should be solved by now
