### ISSUE TITLE
Custom SMTP -> Login method can't see User & Password fields

### ISSUE THREAD

**Issue by yinsenf** [aschroder/Magento-SMTP-Pro-Email-Extension#46]
Custom SMTP -> Login method can't see User & Password fields
Maybe I made mistake somewhere ?
BTW. It was under Magento ver. 1.6.2.0

![2014-07-10 9 45 21 am](https://cloud.githubusercontent.com/assets/4875445/3541952/d36000aa-0851-11e4-9d15-20b92279c2a5.png)

**Comment by giacmir** [comment]
Same here with an old Magento 1.6.2.0 and Firefox 42 on Linux

**Comment by lepiklepik** [comment]
The same problem on Magento 1.7.0.2

**Comment by nvanilkumar** [comment]
I have the same problem in Magento 1.6 version... what is the fix for the problem

**Comment by exceso3** [comment]
Sololution:
edit system.xml in /httpdocs/app/code/local/Aschroder/SMTPPro/etc
remove 
_**<smtp_authentication separator=",">login,plain,crammd5</smtp_authentication>**_
it appears twice, remove both
reload backend page and you'll have username and password

works for me on 1.6
