### ISSUE TITLE
Send mail to friend fail exception fail

### ISSUE THREAD

**Issue by roccodelux** [aschroder/Magento-SMTP-Pro-Email-Extension#48]
Hello, I installed and configured the module in magento with AWS SES. 
Everything works except sending email to a friend. In the shop I have the option send email to a friend, however stmp pro fails. 

In var / log in exception.log <Message> Email address is not verified. </ Message>. 

I do not know how to change the sender with that sender mail  certificate  in AWS SES. 

exception.log 

2014-07-30T10: 39:42 +00:00 ERR (3): 
exception 'Exception' with message '<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/"> 
   <Error> 
     <Type> Sender </ Type> 
     <Code> MessageRejected </ code> 
     <Message> Email address is not verified. </ Message> 
   </ Error> 
   <RequestId> D061552c-17d5-11e4-960F-a33c425613f5 </ RequestId> 
</ ErrorResponse> 
'/ Usr / share / nginx / html / app / code / local / Aschroder / SMTPPro / lib / AmazonSES.php: 108 
Stack trace:

**Comment by sandermangel** [comment]
Hi @roccodelux  I was unable to reproduce this issue on Magento 1.9 with the latest version of the module. Could you confirm this issue still persists for you and perhaps add some more information?
