### ISSUE TITLE
getting 404 not found after install

### ISSUE THREAD

**Issue by phazei** [aschroder/Magento-SMTP-Pro-Email-Extension#49]
I'm running Magento 1.8.1

I just installed master, copied app to the app directory, cleared cache, logged out/in.

When I click System -> Config -> ASCHRODER EXTENSIONS -> SMTP Pro

It takes me to a page with the top menu and the left menu only has the "configuration scope" dropdown.  And the content is "404 error page not found".  I can get to the log though.

Any idea?

**Comment by rafaelsierra** [comment]
I also can confirm that logout and login fix the problem

**Comment by nhim175** [comment]
I confirm that logout and login again will fix the problem
