### ISSUE TITLE
404 error when accessing log with "Add Store Code to Urls” = ON

### ISSUE THREAD

**Issue by mrkrumhausen** [aschroder/Magento-SMTP-Pro-Email-Extension#5]
First of all. Great extension. So helpful!

One problem though, I need to have “Add Store Code to Urls” set to yes, which means that I’m getting a 404 when accessing the log. Any news on a bugfix?

Cheers
Seb

**Comment by sandermangel** [comment]
@mrkrumhausen I could not reproduce this issue on the latest version of Magento 1. Will close the ticket but feel free to open it again if the issue persists for you
