### ISSUE TITLE
Admin SMTP Pro page show "404 Error Page not found" on Magento CE 1.9.0.1

### ISSUE THREAD

**Issue by kamzata** [aschroder/Magento-SMTP-Pro-Email-Extension#56]
In Magento CE 1.9.0.1 Admin --> ASCHRODER EXTENSIONS --> SMTP Pro page show "404 Error Page not found".

I installed the extesion through Magento Connect Manager. Fresh installation of Magento, no other extensions installed. 

Thank you

**Comment by tavinus** [comment]
Boy! I was about to give up on this when I found this post. I had this installed and reinstalled 10 times in different ways. Logout/Login did the trick (I am still getting used to Magento). Even though this is common knowledge for you guys, you may want to give a hint about this on the readme file.
