### ISSUE TITLE
SMTP username + pw autofilled with magento username + pw (safari)

### ISSUE THREAD

**Issue by seangreen** [aschroder/Magento-SMTP-Pro-Email-Extension#65]
When using safari and saving the magento username + pw, the SMTP-Pro SMTP username and pw get replaced. 
It's then easy to accidentally break the smtp connection, when you want to save other settings. (which happened to me.. And yes - the fields are yellow, so I should have noticed. ;))

I now erased the magento username + pw from my keychain - that solves it... but I guess changing the names of the SMTP username + pw fields would be a proper fix.. no?

Sean.

![screen shot 2014-10-21 at 12 24 34](https://cloud.githubusercontent.com/assets/1423486/4716794/90a401ba-590c-11e4-8960-2da79003f275.png)

**Comment by sanderkwantes** [comment]
I have the same issue, the password field is filled in automatically by the osx keychain in safari. It went wrong several times now by me and a client. Anyway to fix it?

**Comment by sandermangel** [comment]
HI @seangreen @sanderkwantes since Magento does not give us an autofill attribute in the backend I'm afraid we can't do a lot about it
