### ISSUE TITLE
stream_socket_enable_crypto not supported under hhvm

### ISSUE THREAD

**Issue by pepijnblom** [aschroder/Magento-SMTP-Pro-Email-Extension#66]
https://github.com/facebook/hhvm/issues/1647

This makes it impossible to send TLS/SSL email using SMTP Pro when using HHVM on the server. Not sure if it's possible but maybe something else could be used instead? 

A test could be added to the Self Test to see if the function exists on the server to at least inform the user SSL/TLS will not be possible.

**Comment by hgati** [comment]
Use ssl not tls
https://github.com/hgati/Magento-SMTP-Pro-Email-Extension/commit/8571187f7f10556454c57aae6917ddc4d990eb84

**Comment by sandermangel** [comment]
This issue has been open for over 3 years. Closing it, if it's still relevant and reproducible please open a new issue
