### ISSUE TITLE
SMTP login details missing

### ISSUE THREAD

**Issue by kithaines** [aschroder/Magento-SMTP-Pro-Email-Extension#68]
![ss 2014-10-28 at 12_31_31](https://cloud.githubusercontent.com/assets/9425372/4802341/7eb26cea-5e42-11e4-8999-5b9047261609.png)
The username/password fields are missing in our install of SMTP Pro.

**Comment by replicahause** [comment]
Hi

Any simplier Method to workaround this issue? I'm facing this exact issue with one of the sites

Thanks

**Comment by aschroder** [comment]
Lots of folks getting this error, none apparently technical enough to debug
it when it's happening to them, and it's not happening to anyone technical
enough to debug it. If it's happening to you at least document these
things:

* your browser + any extensions installed
* Operating system
* and magento version + other extensions.

This might give some clues as to what is causing this.

**Comment by aschroder** [comment]
One user (thanks Andrew) has reported this issue is caused by a conflict with: GoMage Seobooster extension.

Specifically this rewrite:

            <adminhtml>
                <rewrite
<widget_form_element_dependence>GoMage_SeoBooster_Block_Adminhtml_Widget_Form_Element_Dependence</widget_form_element_dependence>
                </rewrite>
            </adminhtml>
