### ISSUE TITLE
5.0.0 Authentication Failed

### ISSUE THREAD

**Issue by robertoartifexsoft** [aschroder/Magento-SMTP-Pro-Email-Extension#80]
Hello,

I am using the module with an Office365 account. I've tested in three environments with the same configuratrion. In local and in testing environments the module runs OK, the mails are sended and there is no error with the test button.
The problem is the production environment. I recive the error: 5.0.0 Authentication Failed, but the configuration is the same as in the other two environments.

Any idea?

Thanks

**Comment by aschroder** [comment]
none sorry - try making a throw-away gmail account like
robertistesting@gmail.com and test sending with that - if that works and
Office doesn't - you know what to do :)

**Comment by robertoartifexsoft** [comment]
Hello,
I've tried with a GMail account and it doesn't work.
This system is a virtual server EC2 on Amazon Web Services. It could be an Amazon restriction?
Thanks!!

**Comment by robertoartifexsoft** [comment]
Hello,

I've checked it was a "security problem" on SMTP Microsoft Account.
It was marked like security fault, and i had to verify the conection.
Now there is no problem.

Thanks for your Help.
