### ISSUE TITLE
Magento 1.9.1 - Support mail queue

### ISSUE THREAD

**Issue by ihor-sviziev** [aschroder/Magento-SMTP-Pro-Email-Extension#82]
I see that in Magento 1.9.1 was added support email queue, but this extension still doesn't support it. Would be great add ability to use mail queues.

**Comment by andrey-legayev** [comment]
:+1:

**Comment by aschroder** [comment]
I've been looking in to how the queue works and will add support in the
next release.

**Comment by aschroder** [comment]
this is now available on github

**Comment by ihor-sviziev** [comment]
@aschroder you didn't created release tag, could you create them? Thanks.
