### ISSUE TITLE
AMAZON SES error

### ISSUE THREAD

**Issue by mavichpe** [aschroder/Magento-SMTP-Pro-Email-Extension#83]
Hi, i am trying to send email through AMAZON SES, but whe i try to send a self test email. I get the follow error.

Either your sending or receiving email address is not verified.
Please check your Amazon SES console and confirm the email addresses are verified and the region matches.

I have AMAZON SES in Production mode, also y setup correctly the IAM user to access to the api. 

I dont know how can i do now. Do you have a solution for this issue?

**Comment by aschroder** [comment]
did you check what region?

**Comment by mavichpe** [comment]
The IAM users are Global. But how can i check  my region?

**Comment by aschroder** [comment]
top right corner when in SES settings in the AWS console

**Comment by mavichpe** [comment]
The SES is in Oregon and the instances are too. But currently i am making some test in a staging server out of the amazon infrastructure. Could be there the problem?

**Comment by aschroder** [comment]
yeh, smtp pro is not multi region, so you'll need to use SES in US East for
smtp pro - check out magesend.com for better Amazon SES support.

**Comment by mavichpe** [comment]
So now i have to request production access to SES on US East region.?

**Comment by mavichpe** [comment]
I change the region on the constructure of the AmazonSES class at the lib folder. Now is work :+1:  thanks
