### ISSUE TITLE
No access to Tools and Self Test if Admin URL is changed

### ISSUE THREAD

**Issue by z3dev** [aschroder/Magento-SMTP-Pro-Email-Extension#84]
As per most advice on the internet, I changed the URL for the administration via app/etc/local.xml

    <admin>
        <routers>
            <adminhtml>
                <args>
                    <frontName><![CDATA[1very1ongur14admin]]></frontName>
                </args>
            </adminhtml>
        </routers>
    </admin>

Most of SMTP Pro operates normally but not these pages...
- System -> Tools -> STMPPro - Email Log
- Configuration -> STMPPro -> Logging and Debugging -> Run Self Test

It's pretty easy to see that the URL to the these pages are NOT using the admin settings.

By the way, using a custom URL for the administration back end allows very easy HTTP server configurations for restricting access. It would be nice if STMPPro followed suit.

**Comment by aschroder** [comment]
should be fixed in the latest release
