### ISSUE TITLE
Add Git Tag 2.0.5

### ISSUE THREAD

**Issue by diglin** [aschroder/Magento-SMTP-Pro-Email-Extension#90]
Hi
it will be great that you had the tag 2.0.5 to your git repo, like that we can use composer more appropriately instead to set dev-master as version requirements

Thanks in advance
Sylvain

**Comment by aschroder** [comment]
done!
https://github.com/aschroder/Magento-SMTP-Pro-Email-Extension/releases/tag/2.0.5
