### ISSUE TITLE
Exception message was: 5.7.1 refused by local policy (MBL-R)

### ISSUE THREAD

**Issue by vroberttaken** [aschroder/Magento-SMTP-Pro-Email-Extension#92]
Hi I have a problem with this extension while testing to send the test mail I get following error:

SMTP Pro Self Test Results
Sending test email to your contact form address: hello@example.com from: info@domain.de. Unable to send test email.
Exception message was: 5.7.1 refused by local policy (MBL-R)
Please check the user guide for frequent error messages and their solutions.
Default templates exist.
Email communications are enabled.
Required database tables exist.

**Comment by aschroder** [comment]
That's coming back from your smtp server: "5.7.1 refused by local policy
(MBL-R)" - ask your server admin to help you debug that one.

**Comment by vroberttaken** [comment]
Hi but thanks for reply, the problem ist still there with all email connection also gmail 

SMTP Pro Self Test Results
Sending test email to your contact form address: hello@example.com from: info@domain.de. Unable to send test email.
Exception message was: 5.7.14 Please log in via your web browser and 5.7.14 then try again. 5.7.14 Learn more at 5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754 v3sm309845wix.8 - gsmtp
Please check the user guide for frequent error messages and their solutions.
Default templates exist.
Email communications are enabled.
Required database tables exist.
Testing failed, please review the reported problems and if you need further help visit
Required database tables exist.....

The Smtp Server works fine

**Comment by aschroder** [comment]
That's a different error message:
"Please log in via your web browser and 5.7.14 then try again. 5.7.14 Learn
more at 5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754"

It's still coming back from your smtp server though - in this case google's
server. Did you read the helpful page Google directed you to? Did that
work?

You'll need to proxy through your server's IP and solve the captcha if you
have managed to get the IP black listed...

**Comment by vroberttaken** [comment]
I noticed something. The error message is still the same

SMTP Pro Self Test Results
Sending test email to your contact form address: hello@example.com from: info@domain.de. Unable to send test email.
Exception message was: 5.7.1 refused by local policy (MBL-R) 
Please check the user guide for frequent error messages and their solutions.


but I am trying to Use SMTP authentication with for ex. another tech@domain.de with pw not info@domain.de. but still the same error like above . But if I use another email than info@domain.de then there should be an error with that new mail. so that should look like

....
Sending test email to your contact form address: hello@example.com from: tech@domain.de. 
....
That is not the case
Still...
...
Sending test email to your contact form address: hello@example.com from: info@domain.de. 
...
I already trying to flush the cache but that don't work any idea how to fix that or where that information is stored. I alreay look at DB but nothing found

**Comment by aschroder** [comment]
Here's my pro-tips for debugging this sort of thing:
1) set up a free trial send grid/MailUp or amazon SES account and try to
connect with that
2) if that works but your SMTP server doesn't, then you have an SMTP server
problem
3) if it does not work, then you have a magento server problem - maybe the
server is intercepting outbound SMTP (for spam prevention purposes).
4) if 3) - consider getting a better host

**Comment by nrvaghasiya** [comment]
SMTP Pro Self Test Results
Sending test email to your contact form address: hello@example.com from: elaunch.magento@gmail.com. Unable to send test email.
Exception message was: Connection refused
Please check the user guide for frequent error messages and their solutions.
Default templates exist.
Email communications are enabled.

i got this error.. on live web hosting..

**Comment by philspbr** [comment]
@vroberttaken Regarding the 5.7.14 error: You have to enable access for less secure apps here: https://www.google.com/settings/u/2/security/lesssecureapps
This will solve your problem.

**Comment by elsondinardo** [comment]
Thank you @philspbr fixed my problem!
