### ISSUE TITLE
"Exception message was: sorry, too many emails (#5.7.1) "

### ISSUE THREAD

**Issue by pmainguet** [aschroder/Magento-SMTP-Pro-Email-Extension#94]
Hi! I'm working with Magento 1.9.1 and the plugin was working great until this morning where I get a "Exception message was: sorry, too many emails (#5.7.1) " when I use the TEST button in Settings.
My mail server (hosted) seems to be OK (no SPAM reporting, no WARNINGs). 
Couldn't find much information about that problem. Could you elaborate on that ?

**Comment by aschroder** [comment]
that message is coming back from your SMTP server - check with the server
admin - maybe you have sent too many (or too quickly) or something...

**Comment by MacCarel** [comment]
Hi there !
Got the same problem. I use OVH Spain webhosting (for my spanish client). 
At first, i used to use general client smtp account to send mails. I tried to create a dedicated account for website. Website is new and sends about 20 mails a day today. 
Problem is totally random, one day all mails will be sent successfully, Another one some mails will be blocked with this message, and another day, any mail will be sent.

OVH told me to sent them technical headers of mails blocked, btu i don(t know where i can find it.

**Comment by sandermangel** [comment]
Hi @MacCarel you can find some details in the smtp_log under System > Tools but the module does not log the full headers I'm afraid
