### ISSUE TITLE
Install problem when Mage_AdminNotification disabled

### ISSUE THREAD

**Issue by indrisepos** [aschroder/Magento-SMTP-Pro-Email-Extension#95]
When the Mage_AdminNotification core modul disabled then I can not install the module. 
@app/code/local/Aschroder/SMTPPro/Helper/Mysql4/Install.php::createInstallNotice()

```
$message = Mage::getModel('adminnotification/inbox');
if($message){
  // $message->setDateAdded(date("c", time () ));
}
```

**Comment by aschroder** [comment]
but If you disable that module you might miss out on all the helpful and
informative messages from eBay Inc. about upcoming conferences and
promotions on PayPal credit schemes...

seriously though, yes good catch, I'll merge your PR in the next release.

**Comment by aschroder** [comment]
merged!
