### ISSUE TITLE
Not send email to customer

### ISSUE THREAD

**Issue by brunowd** [aschroder/Magento-SMTP-Pro-Email-Extension#97]
The client did not receive the order confirmation email, the customer only receives e-mail newsletter and register, but only in the visible User, the password is not;)

**Comment by aschroder** [comment]
are you on 1.9.1? is your cron working?

**Comment by brunowd** [comment]
Hello, cron only in the backend like the image below:
http://s22.postimg.org/hoqxtxwht/cron_no_admin.jpg
I have to enable CRON on the hosting server?

**Comment by brunowd** [comment]
Only need to know the URL of the file you want to update and the update frequency (daily, weekly, etc ...) to change the settings in Magento CRON

**Comment by VoteForNavalny** [comment]
The same here. Cron enabled in magento and installed on a server.

**Comment by sandermangel** [comment]
@brunowd could you provide some more information so we can reproduce the issue?
